name: SQL Validation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  validate_sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Validate SQL Files with SQLFluff
        run: |
          pip install sqlfluff
          sqlfluff lint --dialect ansi files/*.sql
      
      - name: Custom SQL Validation
        run: python custom_sql_validation.py
      
      - name: Handle Results
        run: |
          if [ $? -eq 0 ]; then
            echo "SQL validation succeeded!"
          else
            echo "SQL validation failed!"
          fi